#!/usr/bin/env perl

use Cwd qw(realpath);
use File::Basename qw(dirname);
use lib (dirname(dirname(realpath($0))) . "/etc");
use lib (dirname(realpath($0)) . "/tools/ltng/etc");
use TestTools;

startup("ltng","com.ericsson.ltng.cli.LtngCsvWriter");
